[package]
name = "rempower"
description = "Rust empowered tools"
version = "0.5.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
clap_complete = "4.5.55"
colored = "3.0.0"
