[package]
name = "rempower"
description = "Rust empowered tools"
version = "0.5.4"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
clap_complete = "4.5.58"
colored = "3.0.0"
